VintageAmazonWeb/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VintageAmazon.DataAccess;
using VintageAmazon.DataAccess.Repository.IRepository;
using VintageAmazon.Models;
using VintageAmazon.Utility;

namespace VintageAmazonWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]


public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> objCategoryList = _unitOfWork.Category.GetAll();
            return View(objCategoryList);
        }

        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        //To prevent the cross site request forgery attack (Highly recommended)
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("DisplayOrder", "The Display Order cannot exactly match the Name.");
            }
            //Checks for the validity of the information entered from the user
            if (ModelState.IsValid)
            {
                //Adds the information to the Database
                _unitOfWork.Category.Add(obj);
                //Saves the changes in the Database
                _unitOfWork.Save();
                TempData["success"] = "The category was created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var catergoryFromDb = _db.Categories.Find(id);

            //Other ways to find from DB
            var catergoryFromDbSingle = _unitOfWork.Category.GetFirstOrDefault(x => x.Id == id);
            //var catergoryFromDbFirst = _db.Categories.FirstOrDefault(x => x.Id == id);

            if (catergoryFromDbSingle == null) { return NotFound(); }


            return View(catergoryFromDbSingle);
        }

        //POST
        [HttpPost]
        //To prevent the cross site request forgery attack (Highly recommended)
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("DisplayOrder", "The Display Order cannot exactly match the Name.");
            }
            //Checks for the validity of the information entered from the user
            if (ModelState.IsValid)
            {
                //Updates the information to the Database
                _unitOfWork.Category.Update(obj);
                //Saves the changes in the Database
                _unitOfWork.Save();
                TempData["success"] = "The category was updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var catergoryFromDb = _db.Categories.Find(id);

            //Other ways to find from DB
            //var catergoryFromDbSingle = _db.Categories.SingleOrDefault(x => x.Id == id);
            var catergoryFromDbFirst = _unitOfWork.Category.GetFirstOrDefault(x => x.Id == id);

            if (catergoryFromDbFirst == null) { return NotFound(); }


            return View(catergoryFromDbFirst);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        //To prevent the cross site request forgery attack (Highly recommended)
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Category.GetFirstOrDefault(x => x.Id == id);

            //Checks for the validity of the information
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "The category was removed successfully";

            return RedirectToAction("Index");
        }
    private List<Category> GetSortedCategories()
    {
        return _unitOfWork.Category.OrderBy(c => c.Name).ToList();
    }
}

VintageAmazonWeb/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VintageAmazon.DataAccess;
using VintageAmazon.DataAccess.Repository;
using VintageAmazon.DataAccess.Repository.IRepository;
using VintageAmazon.Models;
using VintageAmazon.Models.ViewModels;

namespace VintageAmazonWeb.Areas.Admin.Controllers;
[Area("Admin")]

public class CompanyController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnviroment;
    public CompanyController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index()
    {
        
        return View();
    }


    //GET
    public IActionResult Upsert(int? id)
    {
        //Tightly binded view
        Company company = new();

        if (id == null || id == 0)
        {
            return View(company);
        }
        else
        {
            company = _unitOfWork.Company.GetFirstOrDefault(i => i.Id == id);
            return View(company);
            //update Company
        }

    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Company obj, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            if(obj.Id == 0)
            {
                _unitOfWork.Company.Add(obj);
                TempData["success"] = "Company was updated successfully";
            }
            else
            {
                _unitOfWork.Company.Update(obj);
            }
            _unitOfWork.Save();
            TempData["success"] = "Company was created successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    
    
    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    { 
        var companyList = _unitOfWork.Company.GetAll();
        return Json(new { data = companyList });
    }

    //POST
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Company.GetFirstOrDefault(x => x.Id == id);
        if (obj == null)
        {
            return Json(new {success = false, message = "Error while deleting"});
        }

        _unitOfWork.Company.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete Successful" });
    }

    #endregion
}

VintageAmazonWeb/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VintageAmazon.DataAccess;
using VintageAmazon.DataAccess.Repository;
using VintageAmazon.DataAccess.Repository.IRepository;
using VintageAmazon.Models;
using VintageAmazon.Models.ViewModels;
using VintageAmazon.Utility;

namespace VintageAmazonWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;


    public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }

    public IActionResult Index()
    {
        return View();
    }

    //GET
    public IActionResult Upsert(int? id)
    {
        ProductVM productVM = new()
        {
            Product = new(),
            CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }),
            CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }),
        };

        if (id == null || id == 0)
        {
            //create product
            //ViewBag.CategoryList = CategoryList;
            //ViewData["CoverTypeList"] = CoverTypeList;
            return View(productVM);
        }
        else
        {
            productVM.Product = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
            return View(productVM);

            //update product
        }


    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(ProductVM obj, IFormFile? file)
    {

        if (ModelState.IsValid)
        {
            string wwwRootPath = _hostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRootPath, @"images\products");
                var extension = Path.GetExtension(file.FileName);

                if (obj.Product.ImageUrl != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                obj.Product.ImageUrl = @"\images\products\" + fileName + extension;

            }
            if (obj.Product.Id == 0)
            {
                _unitOfWork.Product.Add(obj.Product);
            }
            else
            {
                _unitOfWork.Product.Update(obj.Product);
            }
            _unitOfWork.Save();
            TempData["success"] = "Product created successfully";
            return RedirectToAction("Index");
        }
        return View(obj);
    }



    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var productList = _unitOfWork.Product.GetAll(includeProperties: "Category,CoverType");
        return Json(new { data = productList });
    }

    //POST
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Product.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Error while deleting" });
        }

        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }

        _unitOfWork.Product.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Delete Successful" });

    }
    #endregion
}

VintageAmazonWeb/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Numerics;
using System.Security.Claims;
using VintageAmazon.DataAccess.Repository.IRepository;
using VintageAmazon.Utility;

namespace VintageAmazonWeb.ViewComponents
{
    public class ShoppingCartViewComponent: ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if(claim != null)
            {
                if(HttpContext.Session.GetInt32(SD.SessionCart) != null)
                {
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
                else
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

VintageAmazonWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using VintageAmazon.Utility
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VintageAmazonWeb</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VintageAmazonWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">

            <div class="container-fluid">
                <a asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="~/images/amazon-logo.png" height="75px" width="150px" alt="Amazon Logo" loading="lazy" class="nopadding" />
                </a>

                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>

                                </div>
                            </li>
                        }
                        <li class="nav-item">
                                @if (User.IsInRole(SD.Role_Admin))
                                {
                                <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
                                    Manage Orders
                                </a>
                                }
                                else
                                {
                                    <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">
                                        My Orders
                                    </a>
                                }
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <form class="d-flex p" asp-controller="Home" asp-action="Search" data-ajax="true" data-ajax-method="POST">
                        <input class="form-control me-2" name="term" type="search" placeholder="Search">
                        <button class="btn btn-light" type="submit">Search</button>
                    </form>
                    <partial name="_LoginPartial" />

                    @*<form class="d-flex">
                    <input class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="fixed-bottom footer text-muted bg-primary">
        <div class="container">
            &copy; 2023 - VintageAmazonWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/ej4vkmeddp1kokn3ououswyhqla2kfxrwfs0vfzm6vxc3g39/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
@*    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
*@    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNSBp0" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VintageAmazonWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

VintageAmazonWeb/Views/Shared/_StarRatings.cshtml
@model VintageAmazon.Models.Product

<div class="star-ratings">
    <div class="rating">
        @for (int i = 1; i <= 5; i++)
        {
            if (i <= int.Parse(Model.Rating))
            {
                <span class="fa fa-star checked"></span>
            }
            else
            {
                <span class="fa fa-star"></span>
            }
        }
    </div>
    <div class="rating-num">
        (@Model.RateCount)
    </div>
</div>
@*@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
            <br />
            <img src="~/images/StarFade.png" alt="Star Rating" align="middle" id="1" class="rating" itemid="@item.Id" />
            <img src="~/images/StarFade.png" alt="Star Rating" align="middle" id="2" class="rating" itemid="@item.Id" />
            <img src="~/images/StarFade.png" alt="Star Rating" align="middle" id="3" class="rating" itemid="@item.Id" />
            <img src="~/images/StarFade.png" alt="Star Rating" align="middle" id="4" class="rating" itemid="@item.Id" />
            <img src="~/images/StarFade.png" alt="Star Rating" align="middle" id="5" class="rating" itemid="@item.Id" />
            (@item.RateCount)
            @{
                if (item.RateCount > 0)
                {
                    decimal a = @item.RateTotal / item.RateCount;
                    <span class="avr">@a</span>
                }
            }
            <br />
        </td>
    </tr>
}*@


<script type="text/javascript">
    $(function () {
        $("img.rating").mousepver(function(){
            giveRating($(this), "StarGlow.png");
            $(this).css("cursor", "pointer");
        });

        $("img.rating").mouseout(function(){
            giveRating($(this), "StarFade.png");
            refilRating($(this));
        });

        $("img.rating").click(function(e){
            $(this).css('color', 'red');
            var url = "/Product/Home/PostRating?rating=" + parseInt($(this).attr("id") + "&mid=" + parseInt($(this).attr("mid"));
            $.post(url, null, function(data){
                $(e.currentTarget).closest('tr').find('div.result').text(data).css('color','red')
            });
        });
    });

    function giveRating(img, image){
        img.attr("src", "/Images/" + image).prevAll("img.rating").attr("src", "/Images/" + image);
    }

    function refilRating(img1){
        var rt = $(img1).closest('tr').find("span.avr").text();
        var img = $(img1).closest('tr').find("img[id='" + parseInt(rt) + "']");
        img.attr("src", "/images/StarGlow.png").prevAll("img.rating").attr("src", "/images/StarGlow.png");
    }
</script>